### ISSUE TITLE
error when trying to compile with DreamSDK

### ISSUE THREAD

**Issue by megaboy1024** [sizious/dcload-ip#11]
Hi there, I want to build this version of dc-tool to test it out, I'm using DreamSDK running on Windows 10 PC, but when I'm trying to follow up the building instruction I got this compiling error:
$ make
make -C host-src
make[1]: Entering directory `/home/luay_/dcload-ip/host-src'
make -C tool
make[2]: Entering directory `/home/luay_/dcload-ip/host-src/tool'
gcc -O2 -I/usr/local/include -D_WIN32 -DDCLOAD_VERSION=\"2.0.0\" -DDREAMCAST_IP=\"0.0.0.0\" -DHAVE_GETOPT -DSAVE_MY_FANS=0 -DDREAMCAST_BBA_RX_FIFO_DELAY_COUNT=10 -DDREAMCAST_BBA_RX_FIFO_DELAY_TIME=1800 -DDREAMCAST_LAN_RX_FIFO_DELAY_COUNT=1 -DDREAMCAST_LAN_RX_FIFO_DELAY_TIME=1250 -DWITH_BFD  -I/opt/toolchains/dc/sh-elf/include -o dc-tool.o -c dc-tool.c
dc-tool.c: In function 'upload':
dc-tool.c:998:56: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
                     sectsize = bfd_section_size(section);
                                                        ^
dc-tool.c:998:32: error: 'bfd_section_size' undeclared (first use in this function)
                     sectsize = bfd_section_size(section);
                                ^~~~~~~~~~~~~~~~
dc-tool.c:998:32: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [dc-tool.o] Error 1
make[2]: Leaving directory `/home/luay_/dcload-ip/host-src/tool'
make[1]: *** [tool] Error 2
make[1]: Leaving directory `/home/luay_/dcload-ip/host-src'
make: *** [host-src] Error 2

Can you please tell me how to solve it? or if you can provide the build BIN or CDI file to test it out directly.
Thank you

**Comment by sizious** [comment]
Hello,
Thanks for your interest!
Binutils 2.34 included some breaking changes in the BFD library and the functions have changed. I think that you will need to correct the bfd_section_size() call with the older version. [More details is available here](https://gitlab.com/kallistios/dcload-ip/-/commit/c71a5ac98022ce705fac58b86897097b3ed1735e).

**Comment by megaboy1024** [comment]
Thank you very much, it's working perfectly with DHCP enabled :)
